.SILENT:

all: DossierFinal Serveur CreeFichierUtilisateur


Serveur:	Serveur.cpp
			echo Creation serveur
			g++ -o Serveur Serveur.cpp

CreeFichierUtilisateur:	CreeFichierUtilisateur.cpp
						echo Creation CreeFichierUtilisateur
						g++ -o CreeFichierUtilisateur CreeFichierUtilisateur.cpp

DossierFinal:	Main.o Client.o moc_Client.o
				echo Creation dossier final
				g++ -Wl,-R,/usr/local/qt/lib -o DossierFinal2014 Main.o Client.o moc_Client.o -L/usr/local/qt/lib -L/usr/openwin/lib -lqt 

Client.o:	Client.cpp Client.h
			echo Creation client
			g++ -c -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -I/usr/local/qt/mkspecs/default -I. -I. -I/usr/local/qt/include -o Client.o Client.cpp

Main.o:		Main.cpp
			echo Creation Main
			g++ -c -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -I/usr/local/qt/mkspecs/default -I. -I. -I/usr/local/qt/include -o Main.o Main.cpp

moc_Client.o:	moc_Client.cpp
				echo Creation moc_Client
				g++ -c -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -I/usr/local/qt/mkspecs/default -I. -I. -I/usr/local/qt/include -o moc_Client.o moc_Client.cpp
